# Generated by Django 5.1.6 on 2025-02-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('procedure', models.CharField(max_length=1000)),
                ('cuisine', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('meal_type', models.CharField(max_length=100)),
            ],
        ),
    ]
