# Generated by Django 5.1.6 on 2025-02-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0002_cooking_class_remove_recipe_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
