# Generated by Django 5.1.6 on 2025-04-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(choices=[('ADMIN', 'Admin'), ('EVENTS', 'Events'), ('CONTENT', 'Content')], default='ADMIN', max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('images', models.ImageField(default='', upload_to='club_member_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cooking_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed class', max_length=200)),
                ('images', models.ImageField(default='', upload_to='class_images')),
                ('date', models.DateField()),
                ('instructor', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.ImageField(default='', upload_to='recipe_images')),
                ('description', models.TextField(default='')),
                ('difficulty', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('prep_time', models.CharField(default='', max_length=200)),
                ('cook_time', models.CharField(default='', max_length=200)),
                ('total_time', models.CharField(default='', max_length=200)),
                ('serving_size', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('equipment', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
                ('procedure', models.TextField(default='')),
                ('cooking_class_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CookingApp.cooking_class')),
            ],
        ),
    ]
