# Generated by Django 5.1.6 on 2025-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cooking_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='Cooking_Class_Images/')),
                ('date', models.DateField()),
                ('instructor', models.CharField(default='', max_length=200)),
                ('recipes', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(default='', upload_to='Recipe_Images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(default=''),
        ),
    ]
