# Generated by Django 4.2.19 on 2025-02-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0004_cooking_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking_class',
            name='name',
            field=models.CharField(default='unnamed class', max_length=200),
        ),
    ]
