# Generated by Django 4.2.19 on 2025-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0005_alter_cooking_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking_class',
            name='images',
            field=models.ImageField(default='', upload_to='Media/class_images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(default='', upload_to='Media/recipe_images'),
        ),
    ]
