# Generated by Django 5.1.6 on 2025-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0007_alter_cooking_class_images_alter_recipe_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
    ]
