# Generated by Django 5.1.6 on 2025-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0008_club_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_member',
            name='team',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EVENTS', 'Events'), ('CONTENT', 'Content'), ('WEBMASTER', 'Webmaster')], default='ADMIN', max_length=200),
        ),
    ]
