# Generated by Django 5.1.6 on 2025-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0009_club_member_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_member',
            name='images',
            field=models.ImageField(default='', upload_to='club_member_images'),
        ),
        migrations.AlterField(
            model_name='club_member',
            name='team',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EVENTS', 'Events'), ('CONTENT', 'Content')], default='ADMIN', max_length=200),
        ),
    ]
